import Foundation

/// The response from a chat completion request.
///
/// ``ChatResponse`` contains the model's output as ``OutputItem`` values,
/// including messages, tool calls, and reasoning. It also includes
/// ``ResponseStats`` with token usage and performance metrics.
///
/// ## See Also
///
/// - <https://lmstudio.ai/docs/developer/rest/chat#response>
public struct ChatResponse: Codable, Sendable {
    /// Unique identifier for the loaded model instance.
    public let modelInstanceID: String?

    /// Array of output items generated by the model.
    public let output: [OutputItem]?

    /// Token usage and performance statistics.
    public let stats: ResponseStats?

    /// Response identifier when store is true.
    public let responseID: String?

    enum CodingKeys: String, CodingKey {
        case output, stats
        case modelInstanceID = "model_instance_id"
        case responseID = "response_id"
    }
}
